apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hoppscotch.fullname" . }}-admin
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hoppscotch.name" . }}-admin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hoppscotch.name" . }}-admin
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "hoppscotch.extra_labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          {{- if .Values.admin.resources }}
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.readiness }}
          readinessProbe:
            {{- toYaml .Values.admin.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.liveness }}
          livenessProbe:
            {{- toYaml .Values.admin.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.customVolumeMount }}
          volumeMounts:
            {{- toYaml .Values.admin.customVolumeMount | nindent 12 }}
          {{- end }}
      {{- if .Values.admin.nodeSelector }}
      nodeSelector: {{ toYaml .Values.admin.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.tolerations }}
      tolerations: {{ toYaml .Values.admin.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.affinity }}
      affinity: {{ toYaml .Values.admin.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.customVolume }}
      volumes:
        {{- toYaml .Values.admin.customVolume | nindent 12 }}
      {{- end }}