{{- $authList := list -}}
{{- if .Values.parameters.auth.github.enabled -}}
{{- $authList = printf "GITHUB" | append $authList -}}
{{- end -}}
{{- if .Values.parameters.auth.google.enabled -}}
{{- $authList = printf "GOOGLE" | append $authList -}}
{{- end -}}
{{- if .Values.parameters.auth.microsoft.enabled -}}
{{- $authList = printf "MICROSOFT" | append $authList -}}
{{- end -}}
{{- if .Values.parameters.smtp.enabled -}}
{{- $authList = printf "EMAIL" | append $authList -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hoppscotch.fullname" . }}-envs
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
data:
    TOKEN_SALT_COMPLEXITY: "10"
    MAGIC_LINK_TOKEN_VALIDITY: "3"
    REFRESH_TOKEN_VALIDITY: "{{ .Values.parameters.config.refreshTokenValidity }}"
    ACCESS_TOKEN_VALIDITY: "{{ .Values.parameters.config.accessTokenValidity }}"
    ALLOW_SECURE_COOKIES: "{{ .Values.parameters.config.allowSecureToken }}"
    RATE_LIMIT_TTL: "{{ .Values.parameters.config.rateLimit.ttl }}"
    RATE_LIMIT_MAX: "{{ .Values.parameters.config.rateLimit.max }}"
    REDIRECT_URL: {{ if .Values.frontend.ingress.tls }}https://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ else }}http://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ end }}
    WHITELISTED_ORIGINS: {{ if .Values.frontend.ingress.tls }}https://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ else }}http://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ end }},http://localhost:3170,http://localhost:3000,http://localhost:3100
    {{- if $authList }}
    VITE_ALLOWED_AUTH_PROVIDERS: "{{ join "," $authList }}"
    {{- end }}
    {{- if .Values.parameters.auth.google.enabled }}
    GOOGLE_CALLBACK_URL: http://localhost:3170/v1/auth/google/callback
    GOOGLE_SCOPE: {{ .Values.parameters.auth.google.scope }}
    {{- end }}
    {{- if .Values.parameters.auth.github.enabled }}
    GITHUB_CALLBACK_URL: http://localhost:3170/v1/auth/github/callback
    GITHUB_SCOPE: {{ .Values.parameters.auth.github.scope }}
    {{- end }}
    {{- if .Values.parameters.auth.microsoft.enabled }}
    MICROSOFT_CALLBACK_URL: http://localhost:3170/v1/auth/microsoft/callback
    MICROSOFT_SCOPE: {{ .Values.parameters.auth.microsoft.scope }}
    MICROSOFT_TENANT: common
    {{- end }}
    {{- if .Values.parameters.smtp.enabled }}
    MAILER_SMTP_ENABLE: "{{ .Values.parameters.smtp.enabled }}"
    MAILER_USE_CUSTOM_CONFIGS: "true"
    MAILER_ADDRESS_FROM: {{ .Values.parameters.smtp.mailFrom }}
    MAILER_SMTP_HOST: {{ .Values.parameters.smtp.host }}
    MAILER_SMTP_PORT: "{{ .Values.parameters.smtp.port }}"
    MAILER_SMTP_SECURE: "{{ .Values.parameters.smtp.tlsSecure }}"
    MAILER_SMTP_USER: {{ .Values.parameters.smtp.username }}
    MAILER_TLS_REJECT_UNAUTHORIZED: "{{ .Values.parameters.smtp.tlsRejectUnauthorized }}"
    {{- end }}
    VITE_BASE_URL: {{ if .Values.frontend.ingress.tls }}https://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ else }}http://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ end }}
    VITE_SHORTCODE_BASE_URL: {{ if .Values.frontend.ingress.tls }}https://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ else }}http://{{ with (first .Values.frontend.ingress.hosts) }}{{ .host }}{{ end }}{{ end }}
    VITE_ADMIN_URL: http://{{ include "hoppscotch.fullname" . }}-admin:80
    VITE_BACKEND_GQL_URL: http://{{ include "hoppscotch.fullname" . }}-backend:80/graphql
    VITE_BACKEND_WS_URL: wss://{{ include "hoppscotch.fullname" . }}-backend:80/graphql
    VITE_BACKEND_API_URL: http://{{ include "hoppscotch.fullname" . }}-backend:80/v1
    VITE_APP_TOS_LINK: https://docs.hoppscotch.io/support/terms
    VITE_APP_PRIVACY_POLICY_LINK: https://docs.hoppscotch.io/support/privacy
    ENABLE_SUBPATH_BASED_ACCESS: "{{ .Values.parameters.config.enableSubPath }}"
