{{- $fullname := include "hoppscotch.fullname" . -}}
apiVersion: v1
data:
  # Prisma Config
  {{- if .Values.database.enabled -}}
  {{- with .Values.database }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" .username .password .host .port .database | b64enc }}
  {{- end }}
  {{- else }}
  {{- with .Values.database }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .username .password $fullname .database | b64enc }}
  {{- end }}
  {{- end }}
  JWT_SECRET: {{ .Values.parameters.security.jwtSecret | b64enc }}
  SESSION_SECRET: {{ .Values.parameters.security.sessionSecret | b64enc }}
  DATA_ENCRYPTION_KEY: {{ .Values.parameters.security.dataEncryptionKey | b64enc }}
  {{- if .Values.parameters.auth.github.enabled }}
  GITHUB_CLIENT_ID: {{ .Values.parameters.auth.github.clientId | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.parameters.auth.github.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.parameters.auth.google.enabled }}
  GOOGLE_CLIENT_ID: {{ .Values.parameters.auth.google.clientId | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.parameters.auth.google.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.parameters.auth.microsoft.enabled }}
  MICROSOFT_CLIENT_ID: {{ .Values.parameters.auth.microsoft.clientId | b64enc }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.parameters.auth.microsoft.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.parameters.smtp.enabled }}
  MAILER_SMTP_PASSWORD: {{ .Values.parameters.smtp.password | b64enc }}
  {{- end }}
kind: Secret
type: "Opaque"
metadata:
  name: {{ include "hoppscotch.fullname" . }}-envs
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}