apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hoppscotch.fullname" . }}-backend
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hoppscotch.name" . }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hoppscotch.name" . }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "hoppscotch.extra_labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
