apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hoppscotch.fullname" . }}-frontend
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hoppscotch.name" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hoppscotch.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "hoppscotch.extra_labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.containerPort }}
              protocol: TCP
            - name: ws
              containerPort: {{ .Values.frontend.service.containerPort }}
              protocol: TCP
          {{- if .Values.frontend.resources }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.readiness }}
          readinessProbe:
            {{- toYaml .Values.frontend.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.liveness }}
          livenessProbe:
            {{- toYaml .Values.frontend.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.customVolumeMount }}
          volumeMounts:
            {{- toYaml .Values.frontend.customVolumeMount | nindent 12 }}
          {{- end }}
      {{- if .Values.frontend.nodeSelector }}
      nodeSelector: {{ toYaml .Values.frontend.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.tolerations }}
      tolerations: {{ toYaml .Values.frontend.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.affinity }}
      affinity: {{ toYaml .Values.frontend.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.customVolume }}
      volumes:
        {{- toYaml .Values.frontend.customVolume | nindent 12 }}
      {{- end }}