apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoppscotch.fullname" . }}-frontend
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hoppscotch.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
