# @schema
# type: string
# @schema
# -- the override name
nameOverride: ""
fullnameOverride: ""

# Postgresql Database configuration. We do not recommend to use this configuration for production environment.
postgresql:
  # @schema
  # type: bool
  # @schema
  # -- Enable the internal PostgreSQL installation
  enabled: true
  
  # @schema
  # type: object
  # @schema
  # -- Configure the authentication of the instance
  auth:
    postgresPassword: hoppscotch
    username: hoppscotch
    password: hoppscotch
    database: hoppscotch

  # -- Instance configurations, resources, affinity, persistence and others.
  primary:
    resources: {}
    affinity: {}
    nodeSelector: {}
    tolerations: []
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""
      annotations: {}
      labels: {}

# -- External Database configuration, Configure the database for production environment.
database:
  enabled: false
  username: hoppscotch
  password: hoppscotch
  host: 127.0.0.1
  port: 5432
  database: hoppscotch

# Parameters configuration
parameters:
  # -- Security
  security:
    jwtSecret: ""
    sessionSecret: ""
    dataEncryptionKey: "" # 32 charsets
  
  # -- Configs
  config:
    refreshTokenValidity: "604800000"
    accessTokenValidity: "86400000"
    allowSecureToken: true
    enableSubPath: false
    rateLimit:
      ttl: 60 # In seconds
      max: 100 # Max requests per IP
  
  # -- Auth Providers
  auth:
    github:
      enabled: false
      clientId: ""
      clientSecret: ""
      scope: user:email
    google:
      enabled: false
      clientId: ""
      clientSecret: ""
      scope: user:email
    microsoft:
      enabled: false
      clientId: ""
      clientSecret: ""
      scope: user:email
  
  # -- SMTP configurations
  smtp:
    enabled: false
    mailFrom: "<no_reply@example.com>"
    host: localhost
    port: 25
    tlsSecure: false
    tlsRejectUnauthorized: false
    username: ""
    password: ""

# -- Parameters secrets (exists) configuration. In case that you already has the secret configured.
parametersSecretName: ""

# Backend configuration
backend:
  # -- Number of replicas for the backend
  replicaCount: 1

  # -- The image and tag used by backend
  image:
    repository: hoppscotch/hoppscotch-backend
    tag: 2024.12.0
    pullPolicy: IfNotPresent

  # -- Extra labels used by backend
  extra_labels: {}
  #   app: "postwoman"
  #   env: "staging"

  # -- Service configuration
  service:
    type: ClusterIP
    port: 80
    containerPort: 3170

  # -- Ingress configuration
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: ["/"]
    tls: []

  # -- Configure app resources: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # -- Configure app liveness: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  liveness:
    httpGet:
      path: /
      port: http
  
  # -- Configure app readiness: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  readiness:
    httpGet:
      path: /
      port: http

  # -- Configure app node selector: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  nodeSelector: {}

  # -- Configure app tolerations: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []

  # -- Configure app affinity: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  affinity: {}

  # -- Configure app custom volume mounts: https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
  customVolumeMount: {}

  # -- Configure app custom volume: https://kubernetes.io/docs/concepts/storage/volumes/
  customVolume: {}

# Frontend configuration
frontend:
  # -- Number of replicas for the frontend
  replicaCount: 1

  # -- The image and tag used by frontend
  image:
    repository: hoppscotch/hoppscotch-frontend
    tag: 2024.12.0
    pullPolicy: IfNotPresent

  # -- Extra labels used by frontend
  extra_labels: {}
  #   app: "postwoman"
  #   env: "staging"

  # -- Service configuration
  service:
    type: ClusterIP
    port: 80
    containerPort: 3000

  # -- Ingress configuration
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: ["/"]
    tls: []

  # -- Configure app resources: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # -- Configure app liveness: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  liveness:
    httpGet:
      path: /
      port: http
  
  # -- Configure app readiness: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  readiness:
    httpGet:
      path: /
      port: http

  # -- Configure app node selector: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  nodeSelector: {}

  # -- Configure app tolerations: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []

  # -- Configure app affinity: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  affinity: {}

  # -- Configure app custom volume mounts: https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
  customVolumeMount: {}

  # -- Configure app custom volume: https://kubernetes.io/docs/concepts/storage/volumes/
  customVolume: {}

# Admin configuration
admin:
  # -- Number of replicas for the admin
  replicaCount: 1

  # -- The image and tag used by admin
  image:
    repository: hoppscotch/hoppscotch-admin
    tag: 2024.12.0
    pullPolicy: IfNotPresent

  # -- Extra labels used by admin
  extra_labels: {}
  #   app: "postwoman"
  #   env: "staging"

  # -- Service configuration
  service:
    type: ClusterIP
    port: 80
    containerPort: 3100

  # -- Ingress configuration
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: ["/"]
    tls: []

  # -- Configure app resources: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # -- Configure app liveness: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  liveness:
    httpGet:
      path: /
      port: http
  
  # -- Configure app readiness: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  readiness:
    httpGet:
      path: /
      port: http

  # -- Configure app node selector: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  nodeSelector: {}

  # -- Configure app tolerations: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []

  # -- Configure app affinity: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  affinity: {}

  # -- Configure app custom volume mounts: https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
  customVolumeMount: {}

  # -- Configure app custom volume: https://kubernetes.io/docs/concepts/storage/volumes/
  customVolume: {}
